version: "3.7"

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - AWS_REGION=ap-northeast-2
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
      - AWS_SQS_QUEUE_URL=http://localhost:4566/000000000000/example
      - DATABASE_LOGGING=true
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=nest
      - DATABASE_USER=root
      - DATABASE_PASSWORD=test
      - DATABASE_SYNC=true
      - EMAIL=no-reply@example.com
      - PORT=5000
    volumes:
      - ./src:/app/src:ro
      - ./libs:/app/libs:ro

  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=test
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/nest:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=ses,sqs,sns
      - AWS_DEFAULT_REGION=ap-northeast-2
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d:ro
